#!C:\Program Files\nodejs\node.exe
let process = require("process");
let child_process= require("child_process");
const { ESLint } = require('eslint');

function exec() {
    return new Promise(function(resolve) {
        child_process.exec(name, resolve);
    })
}

(async function main() {
    // Create an instance
    const eslint = new ESLint({ fix: false });

    // Lint files
    await exec("git stash push -k");
    const results = await eslint.lintFiles(['index.js']);
    await exec("git stash pop");
    
    // Format the results
    const formatter = await eslint.loadFormatter('stylish');
    const resultText = formatter.format(results);

    console.log(resultText);

    for (let result of results) {
        if (result.errorCount) {
            process.exitCode = 1;
        }
    }
})().catch((error) => {
    process.exitCode = 1;
    console.log(error);
})
